"""Generate original antialiased launcher artwork and full-bleed RGB565 wallpaper.

The PNGs are asset inspections; scripts/preview-ui.ps1 renders them with LVGL.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter
import math
ROOT = Path(__file__).resolve().parents[1]
SIZE, SCALE = 80, 4
OUT = ROOT / '.cache/ui-preview'
OUT.mkdir(parents=True, exist_ok=True)
COLORS = {'settings':((107,144,255),(49,75,182)), 'clock':((55,211,185),(16,123,130)), 'network':((88,193,253),(34,98,194)), 'about':((192,146,255),(115,70,182)), 'codex':((55,172,155),(18,85,93)), 'fitness':((64,151,244),(24,66,122))}

def write_changed(path, source):
    if not path.exists() or path.read_text(encoding='utf-8-sig') != source:
        path.write_text(source,encoding='utf-8')

def emit_image(name, image, alpha):
    rgb, mask = [], []
    for r,g,b,a in image.convert('RGBA').getdata():
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        rgb.extend((v & 255,v >> 8)); mask.append(a)
    data = rgb + mask if alpha else rgb
    w,h = image.size
    rows = ['    '+','.join(map(str,data[i:i+32]))+',' for i in range(0,len(data),32)]
    return '\n'.join(['static const uint8_t '+name+'_pixels[] = {',*rows,'};',f'const lv_image_dsc_t {name} = {{ .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_{"RGB565A8" if alpha else "RGB565"}, .w = {w}, .h = {h}, .stride = {w*2}}}, .data_size = sizeof({name}_pixels), .data = {name}_pixels }};'])

def icon(kind, colors):
    n = SIZE*SCALE
    im = Image.new('RGBA',(n,n))
    mask = Image.new('L',(n,n)); d = ImageDraw.Draw(mask)
    d.rounded_rectangle((4*SCALE,3*SCALE,76*SCALE-1,75*SCALE-1),21*SCALE,fill=255)
    top,bot = colors
    pix = im.load()
    for y in range(n):
        for x in range(n):
            t=y/(n-1)
            glow=12*math.exp(-((x/n-.23)**2+(y/n-.18)**2)/.08)
            pix[x,y]=tuple(min(255,int(top[i]*(1-t)+bot[i]*t+glow)) for i in range(3))+(mask.getpixel((x,y)),)
    glyph = Image.new('RGBA',im.size); g=ImageDraw.Draw(glyph)
    def line(points,w=3.2):
        pts=[(int(x*SCALE),int(y*SCALE)) for x,y in points]
        g.line(pts,fill=(244,253,255,255),width=int(w*SCALE),joint='curve')
        rad=w*SCALE/2
        for x,y in (pts[0],pts[-1]):g.ellipse((x-rad,y-rad,x+rad,y+rad),fill=(244,253,255,255))
    def ellipse(box,w=3.2,fill=None):g.ellipse(tuple(int(v*SCALE) for v in box),fill=fill,outline=None if fill else (244,253,255,255),width=int(w*SCALE))
    if kind=='settings':
        points=[]
        for i in range(64):
            a=i*math.pi/32; r=22 if i%8 in (1,2,3,4) else 18
            points.append((int((40+math.cos(a)*r)*SCALE),int((39+math.sin(a)*r)*SCALE)))
        g.polygon(points,fill=(244,253,255,255))
        # Cut the centre out of the glyph layer so the gradient shines through.
        g.ellipse((31*SCALE,30*SCALE,49*SCALE,48*SCALE),fill=(0,0,0,0))
    elif kind=='clock':
        ellipse((17,16,63,62)); line([(40,24),(40,39),(51,46)])
        for x,y in [(40,20),(40,58),(21,39),(59,39)]:ellipse((x-1,y-1,x+1,y+1),fill=(244,253,255,230))
    elif kind=='network':
        for r in (14,26,38):g.arc(tuple(int(v*SCALE) for v in (40-r,55-r,40+r,55+r)),218,322,fill=(244,253,255,255),width=3*SCALE)
        ellipse((37,52,43,58),fill=(244,253,255,255))
    elif kind=='about':
        ellipse((18,17,62,61)); ellipse((38,27,42,31),fill=(244,253,255,255));line([(40,38),(40,51)]);line([(36,51),(44,51)],2.8)
    elif kind=='fitness':
        line([(20,39),(60,39)],5)
        for x in (21,59):
            g.rounded_rectangle(((x-5)*SCALE,24*SCALE,(x+5)*SCALE,54*SCALE),3*SCALE,fill=(244,253,255,255))
        for x in (13,67):line([(x,31),(x,47)],3.5)
    else:
        g.rounded_rectangle((16*SCALE,19*SCALE,64*SCALE,59*SCALE),7*SCALE,outline=(244,253,255,255),width=3*SCALE)
        line([(26,31),(34,39),(26,47)],2.8);line([(42,47),(54,47)],2.8)
    im=Image.alpha_composite(im,glyph)
    return im.resize((SIZE,SIZE),Image.Resampling.LANCZOS)

source=['#include "lvgl.h"','// Generated by scripts/generate_icons.py; RGB565 + separate A8 alpha plane.']
for kind,colors in COLORS.items():
    im=icon(kind,colors); im.save(OUT/(kind+'.png'))
    source.append(emit_image('icon_'+kind,im,True))
write_changed(ROOT/'firmware/main/app_icons.c','\n'.join(source)+'\n')
bg=Image.new('RGB',(360,360)); p=bg.load()
for y in range(360):
    for x in range(360):
        t=y/359
        glow=math.exp(-((x-290)**2+(y-260)**2)/34000)
        # Full canvas coverage, no vignette or opaque circular edge.
        wave=1.8*math.sin(x/45+y/64)
        p[x,y]=(int(15+4*t+3*glow+wave),int(27+10*t+30*glow+wave),int(51+12*t+29*glow+wave))
bg.save(OUT/'wallpaper.png')
write_changed(ROOT/'firmware/main/dark/scr_bg.c','#include "lvgl.h"\n// Full-bleed original wallpaper generated by scripts/generate_icons.py.\n'+emit_image('scr_bg',bg,False)+'\n')
print(f'Generated {len(COLORS)} transparent 80px icons and 360px wallpaper')
